name: django-docker-container

services:
  app:
    build: .
    image: django-docker-container-image:v0.1.0
    ports:
      - "8001:8000"
    env_file:
      - ./.env.dev
    volumes:
      - ./src:/app
      - dev-db-data:/app/db

volumes:
  dev-db-data:
