# Generated by Django 5.2.4 on 2025-07-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='content',
            field=models.TextField(help_text='Content is stored in HTML format.', verbose_name='Content'),
        ),
    ]
