# Generated by Django 5.2.4 on 2025-07-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0002_alter_homepagecontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='content',
            field=models.TextField(help_text='Content can be written in Markdown or HTML. It will be rendered as HTML on the home page.', verbose_name='Content'),
        ),
    ]
