# Generated by Django 5.2.4 on 2025-07-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0004_alter_homepagecontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='content',
            field=models.TextField(help_text='Content can be written in Markdown or HTML. To parse Markdown inside an HTML block, add the attribute `markdown="1"` to the tag. Example: &lt;div markdown="1"&gt;# A Header&lt;/div&gt;. Note: Use the "Source Code" view in the editor when adding blocks with `markdown="1"`.', verbose_name='Content'),
        ),
    ]
